CREATE SCHEMA IF NOT EXISTS RAW;
CREATE SCHEMA IF NOT EXISTS STAGING;
CREATE SCHEMA IF NOT EXISTS MARTS;

CREATE OR REPLACE FILE FORMAT RAW.CSV_STANDARD
    TYPE = CSV
    FIELD_DELIMITER = ','
    SKIP_HEADER = 1
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
    NULL_IF = ('', 'NULL', 'null')
    TRIM_SPACE = TRUE;

CREATE STAGE IF NOT EXISTS RAW.SBA_STAGE
    FILE_FORMAT = RAW.CSV_STANDARD;
