table data_quality_report
	column check_name
		dataType: string
		summarizeBy: none
		sourceColumn: check_name
	column status
		dataType: string
		summarizeBy: none
		sourceColumn: status
	column failed_count
		dataType: int64
		formatString: #,0
		summarizeBy: sum
		sourceColumn: failed_count
	column details
		dataType: string
		summarizeBy: none
		sourceColumn: details
	partition data_quality_report = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents(DataRoot & "\quality\data_quality_report.csv"), [Delimiter = ",", Columns = 4, Encoding = 65001, QuoteStyle = QuoteStyle.Csv]),
				    PromotedHeaders = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
				    ChangedType = Table.TransformColumnTypes(PromotedHeaders, {{"check_name", type text}, {"status", type text}, {"failed_count", Int64.Type}, {"details", type text}})
				in
				    ChangedType
