table dim_geography
	column geography_key
		dataType: int64
		summarizeBy: none
		sourceColumn: geography_key
	column state
		dataType: string
		summarizeBy: none
		sourceColumn: state
	column county
		dataType: string
		summarizeBy: none
		sourceColumn: county
	column region
		dataType: string
		summarizeBy: none
		sourceColumn: region
	partition dim_geography = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents(DataRoot & "\warehouse\dim_geography.csv"), [Delimiter = ",", Columns = 4, Encoding = 65001, QuoteStyle = QuoteStyle.Csv]),
				    PromotedHeaders = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
				    ChangedType = Table.TransformColumnTypes(PromotedHeaders, {{"geography_key", Int64.Type}, {"state", type text}, {"county", type text}, {"region", type text}})
				in
				    ChangedType
