table dim_lender
	column lender_key
		dataType: int64
		summarizeBy: none
		sourceColumn: lender_key
	column lender_name
		dataType: string
		summarizeBy: none
		sourceColumn: lender_name
	column lender_city
		dataType: string
		summarizeBy: none
		sourceColumn: lender_city
	column lender_state
		dataType: string
		summarizeBy: none
		sourceColumn: lender_state
	partition dim_lender = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents(DataRoot & "\warehouse\dim_lender.csv"), [Delimiter = ",", Columns = 4, Encoding = 65001, QuoteStyle = QuoteStyle.Csv]),
				    PromotedHeaders = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
				    ChangedType = Table.TransformColumnTypes(PromotedHeaders, {{"lender_key", Int64.Type}, {"lender_name", type text}, {"lender_city", type text}, {"lender_state", type text}})
				in
				    ChangedType
