table fact_lending_activity
	measure 'Total Approved Dollars' =
			SUM(fact_lending_activity[approved_dollars])
		formatString: \$#,0;(\$#,0);\$#,0
	measure 'Total Loan Count' =
			SUM(fact_lending_activity[approved_loan_count])
		formatString: #,0
	measure 'Average Loan Size' =
			DIVIDE(
			    [Total Approved Dollars],
			    [Total Loan Count]
			)
		formatString: \$#,0;(\$#,0);\$#,0
	measure 'Total Guaranty Dollars' =
			SUM(fact_lending_activity[guaranty_dollars])
		formatString: \$#,0;(\$#,0);\$#,0
	measure 'Guaranty Rate' =
			DIVIDE(
			    [Total Guaranty Dollars],
			    [Total Approved Dollars]
			)
		formatString: 0.00%
	measure 'Lender Share' =
			DIVIDE(
			    [Total Approved Dollars],
			    CALCULATE(
			        [Total Approved Dollars],
			        ALL(dim_lender)
			    )
			)
		formatString: 0.00%
	measure 'Active Lenders' =
			DISTINCTCOUNT(dim_lender[lender_key])
		formatString: #,0
	measure 'Top 10 Lender Dollars' =
			SUMX(
			    TOPN(
			        10,
			        ALL(dim_lender[lender_name]),
			        [Total Approved Dollars],
			        DESC
			    ),
			    [Total Approved Dollars]
			)
		formatString: \$#,0;(\$#,0);\$#,0
	measure 'Top 10 Lender Share' =
			DIVIDE(
			    [Top 10 Lender Dollars],
			    CALCULATE(
			        [Total Approved Dollars],
			        ALL(dim_lender)
			    )
			)
		formatString: 0.00%
	measure 'Failed Data Quality Checks' =
			COUNTROWS(
			    FILTER(
			        data_quality_report,
			        data_quality_report[status] <> "pass"
			    )
			)
		formatString: #,0
	measure 'Rejected Record Count' =
			COUNTROWS(rejected_records)
		formatString: #,0
	column lender_key
		dataType: int64
		summarizeBy: none
		sourceColumn: lender_key
	column geography_key
		dataType: int64
		summarizeBy: none
		sourceColumn: geography_key
	column date_key
		dataType: int64
		summarizeBy: none
		sourceColumn: date_key
	column reporting_period
		dataType: dateTime
		formatString: Short Date
		summarizeBy: none
		sourceColumn: reporting_period
	column approved_loan_count
		dataType: int64
		formatString: #,0
		summarizeBy: sum
		sourceColumn: approved_loan_count
	column approved_dollars
		dataType: double
		formatString: \$#,0;(\$#,0);\$#,0
		summarizeBy: sum
		sourceColumn: approved_dollars
	column guaranty_dollars
		dataType: double
		formatString: \$#,0;(\$#,0);\$#,0
		summarizeBy: sum
		sourceColumn: guaranty_dollars
	partition fact_lending_activity = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents(DataRoot & "\warehouse\fact_lending_activity.csv"), [Delimiter = ",", Columns = 7, Encoding = 65001, QuoteStyle = QuoteStyle.Csv]),
				    PromotedHeaders = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
				    ChangedType = Table.TransformColumnTypes(PromotedHeaders, {{"lender_key", Int64.Type}, {"geography_key", Int64.Type}, {"date_key", Int64.Type}, {"reporting_period", type date}, {"approved_loan_count", Int64.Type}, {"approved_dollars", type number}, {"guaranty_dollars", type number}})
				in
				    ChangedType
